const animals = [
  "dog",
  "cat",
  "horse",
  "cow",
  "sheep",
  "goat",
  "pig",
  "donkey",
  "camel",
  "llama",
  "alpaca",
  "buffalo",
  "bison",
  "yak",
  "zebra",
  "giraffe",
  "elephant",
  "rhino",
  "hippo",
  "lion",
  "tiger",
  "leopard",
  "cheetah",
  "panther",
  "jaguar",
  "cougar",
  "lynx",
  "bobcat",
  "ocelot",
  "caracal",
  "wolf",
  "fox",
  "coyote",
  "jackal",
  "hyena",
  "dingo",
  "bear",
  "panda",
  "koala",
  "kangaroo",
  "wallaby",
  "wombat",
  "platypus",
  "echidna",
  "opossum",
  "armadillo",
  "sloth",
  "anteater",
  "aardvark",
  "pangolin",
  "otter",
  "beaver",
  "badger",
  "weasel",
  "ferret",
  "marten",
  "mink",
  "stoat",
  "wolverine",
  "skunk",
  "raccoon",
  "coati",
  "kinkajou",
  "ringtail",
  "civet",
  "genet",
  "mongoose",
  "meerkat",
  "suricate",
  "lemur",
  "ayeaye",
  "tarsier",
  "loris",
  "galago",
  "monkey",
  "baboon",
  "mandrill",
  "macaque",
  "chimpanzee",
  "gorilla",
  "orangutan",
  "gibbon",
  "siamang",
  "bonobo",
  "howler",
  "capuchin",
  "marmoset",
  "tamarin",
  "saki",
  "uakari",
  "squirrel",
  "chipmunk",
  "prairiedog",
  "marmot",
  "groundhog",
  "gerbil",
  "hamster",
  "mouse",
  "rat",
  "vole",
  "lemming",
  "porcupine",
  "hedgehog",
  "shrew",
  "mole",
  "bat",
  "flyingfox",
  "vampirebat",
  "fruitbat",
  "whale",
  "dolphin",
  "porpoise",
  "narwhal",
  "beluga",
  "orca",
  "manatee",
  "dugong",
  "seal",
  "sealion",
  "walrus",
  "otariid",
  "phocid",
  "elephantseal",
  "furseal",
  "deer",
  "elk",
  "moose",
  "reindeer",
  "caribou",
  "antelope",
  "gazelle",
  "impala",
  "kudu",
  "oryx",
  "eland",
  "springbok",
  "gnu",
  "wildebeest",
  "ibex",
  "chamois",
  "tahr",
  "markhor",
  "bharal",
  "muskox",
  "saiga",
  "tapir",
  "okapi",
  "hippopotamus",
  "boar",
  "warthog",
  "peccary",
  "capybara",
  "agouti",
  "paca",
  "chinchilla",
  "viscacha",
  "nutria",
  "muskrat",
  "jerboa",
  "hamster",
  "fossa",
  "tenrec",
  "desman",
  "zorilla",
  "polecat",
  "cuscus",
  "quokka",
  "bandicoot",
  "bilby",
  "num bat",
  "tasmanianwolf",
  "tasmaniandevil",
  "quoll",
  "tree shrew",
  "colugo",
  "pangolin",
  "sunbear",
  "slothbear",
  "spectacledbear",
  "polar bear",
  "grizzly",
  "blackbear",
  "redpanda",
  "snowleopard",
  "cloudedleopard",
  "serval",
  "sandcat",
  "pallascat",
  "marbledcat",
  "fishingcat",
  "flatheadedcat",
  "goldenjackal",
  "arcticfox",
  "fennec",
  "manedwolf",
  "bushdog",
  "dhole",
  "hartebeest",
  "dikdik",
  "klipspringer",
  "waterbuck",
  "nyala",
  "bongo",
  "duiker",
  "sitatunga",
  "goral",
  "serow",
  "tak in",
  "anoa",
  "babirusa",
  "sparrow",
  "robin",
  "pigeon",
  "dove",
  "crow",
  "raven",
  "magpie",
  "starling",
  "blackbird",
  "finch",
  "canary",
  "cardinal",
  "bluejay",
  "jay",
  "oriole",
  "lark",
  "swallow",
  "swift",
  "martin",
  "warbler",
  "wren",
  "chickadee",
  "titmouse",
  "nuthatch",
  "creeper",
  "goldfinch",
  "bullfinch",
  "crossbill",
  "siskin",
  "bunting",
  "grosbeak",
  "towhee",
  "junco",
  "waxwing",
  "thrush",
  "nightingale",
  "mockingbird",
  "lyrebird",
  "skylark",
  "pipit",
  "eagle",
  "falcon",
  "hawk",
  "kestrel",
  "buzzard",
  "harrier",
  "osprey",
  "kite",
  "condor",
  "vulture",
  "owl",
  "barnowl",
  "snowyowl",
  "screechowl",
  "hornedowl",
  "burrowingowl",
  "tawnyowl",
  "scopsowl",
  "fishowl",
  "owlet",
  "parrot",
  "macaw",
  "cockatoo",
  "cockatiel",
  "budgie",
  "lovebird",
  "lorikeet",
  "conure",
  "parakeet",
  "rosella",
  "finchbill",
  "hornbill",
  "toucan",
  "trogon",
  "quetzal",
  "kingfisher",
  "roller",
  "beeater",
  "hoopoe",
  "motmot",
  "woodpecker",
  "flicker",
  "sapsucker",
  "piculet",
  "wryneck",
  "treecreeper",
  "barbet",
  "jacamar",
  "puffbird",
  "nunbird",
  "penguin",
  "auk",
  "puffin",
  "guillemot",
  "razorbill",
  "albatross",
  "petrel",
  "shearwater",
  "fulmar",
  "prion",
  "seagull",
  "tern",
  "skimmer",
  "kittiwake",
  "frigatebird",
  "booby",
  "gannet",
  "cormorant",
  "anhinga",
  "pelican",
  "duck",
  "goose",
  "swan",
  "teal",
  "mallard",
  "pochard",
  "eider",
  "scoter",
  "merganser",
  "goldeneye",
  "turkey",
  "chicken",
  "quail",
  "pheasant",
  "partridge",
  "grouse",
  "ptarmigan",
  "peafowl",
  "guineafowl",
  "curassow",
  "crane",
  "stork",
  "heron",
  "egret",
  "bittern",
  "ibis",
  "spoonbill",
  "flamingo",
  "shoebill",
  "jabiru",
  "rail",
  "coot",
  "moorhen",
  "gallinule",
  "crake",
  "lapwing",
  "plover",
  "dotterel",
  "oystercatcher",
  "turnstone",
  "sandpiper",
  "snipe",
  "curlew",
  "godwit",
  "avocet",
  "stilts",
  "phalarope",
  "jacana",
  "thickknee",
  "pratincole",
  "kiwi",
  "emu",
  "ostrich",
  "cassowary",
  "rhea",
  "tinamou",
  "hoatzin",
  "seriema",
  "sunbittern",
  "kagu",
  "cuckoo",
  "roadrunner",
  "coucal",
  "anis",
  "koel",
  "turaco",
  "mousebird",
  "hornbill",
  "secretarybird",
  "bushbird",
  "manakin",
  "cotinga",
  "antbird",
  "antwren",
  "antshrike",
  "tapaculo",
  "ovenbird",
  "leafbird",
  "ioras",
  "babbler",
  "bulbul",
  "drongo",
  "fantail",
  "monarch",
  "whistler",
  "shrike",
  "butcherbird",
  "bowerbird",
  "fairywren",
  "honeyeater",
  "sunbird",
  "flowerpecker",
  "sugarbird",
  "whiteeye",
  "bellbird",
  "riflebird",
  "birdofparadise",
  "lyrebird",
  "scrubbird",
  "thornbill",
  "crocodile",
  "alligator",
  "caiman",
  "gharials",
  "gavial",
  "lizard",
  "gecko",
  "iguana",
  "chameleon",
  "anole",
  "skink",
  "monitor",
  "tegu",
  "basilisk",
  "agama",
  "uromastyx",
  "draco",
  "tokay",
  "leopardgecko",
  "crestedgecko",
  "daygecko",
  "fence lizard",
  "hornedlizard",
  "glasslizard",
  "slowworm",
  "armadillolizard",
  "girdledlizard",
  "nightlizard",
  "lacerta",
  "podarcis",
  "snake",
  "python",
  "boa",
  "anaconda",
  "viper",
  "adder",
  "cobra",
  "mamba",
  "krait",
  "rattlesnake",
  "copperhead",
  "cottonmouth",
  "ferdelance",
  "gaboon",
  "sidewinder",
  "boomslang",
  "taipan",
  "deathadder",
  "kingsnake",
  "milksnake",
  "cornsnake",
  "ratsnake",
  "bullsnake",
  "coachwhip",
  "gartersnake",
  "watersnake",
  "mudsnake",
  "greensnake",
  "vine snake",
  "treesnake",
  "blind snake",
  "seasnake",
  "seakrait",
  "sandboa",
  "rosyboa",
  "rubberboa",
  "burmesepython",
  "reticulatedpython",
  "ballpython",
  "rockpython",
  "turtle",
  "tortoise",
  "terrapin",
  "box turtle",
  "snappingturtle",
  "softshell",
  "spinysoftshell",
  "leatherturtle",
  "greenturtle",
  "hawksbill",
  "loggerhead",
  "ridley",
  "oliveturtle",
  "flatback",
  "seaturtle",
  "mapturtle",
  "paintedturtle",
  "woodturtle",
  "bogturtle",
  "mudturtle",
  "slider",
  "cooter",
  "diamondback",
  "malaclemys",
  "chelonian",
  "sideneck",
  "matamata",
  "flyriver",
  "pig nose",
  "asianbox",
  "lizardfish",
  "skinkfish",
  "geckofish",
  "iguanafish",
  "monitorfish",
  "watermonitor",
  "komodo",
  "perentie",
  "lace monitor",
  "savannahmonitor",
  "blackthroat",
  "whitethroat",
  "ackie",
  "tree monitor",
  "emeraldmonitor",
  "crocmonitor",
  "mangrove",
  "sandmonitor",
  "rockmonitor",
  "nilemonitor",
  "chameleonfish",
  "pantherchameleon",
  "veiledchameleon",
  "jacksonchameleon",
  "pygmychameleon",
  "leafchameleon",
  "parsonii",
  "calumma",
  "furcifer",
  "brookesia",
  "geckolizard",
  "housegecko",
  "tokaygecko",
  "daygecko",
  "golden gecko",
  "bandedgecko",
  "fat tailed",
  "knobtailed",
  "leaf tailed",
  "flyinggecko",
  "iguana lizard",
  "greeniguana",
  "marineiguana",
  "desertiguana",
  "spinytailed",
  "rockiguana",
  "cyclura",
  "ctenosaura",
  "chuckwalla",
  "hornediguana",
  "agama lizard",
  "beardeddragon",
  "frilleddragon",
  "waterdragon",
  "rankins",
  "rockagama",
  "redheaded",
  "bluehead",
  "collared",
  "butterfly",
  "skinklizard",
  "bluetongue",
  "shingleback",
  "fire skink",
  "sand skink",
  "five lined",
  "platedlizard",
  "sun skink",
  "emerald skink",
  "mabuya",
  "crocodilian",
  "saltwatercroc",
  "freshwatercroc",
  "americancroc",
  "siamese",
  "mugger",
  "orinoco",
  "philippine",
  "falsegharial",
  "tomistoma",
  "tortoise",
  "galapagos",
  "aldabra",
  "leopardtortoise",
  "sulcata",
  "radiated",
  "indianstar",
  "russiantortoise",
  "greek",
  "hermann",
  "gopher",
  "deserttortoise",
  "pancake",
  "marginated",
  "egyptian",
  "spurred",
  "burmesestar",
  "forsten",
  "angulate",
  "chaco",
  "snakehead",
  "pythonhead",
  "viperhead",
  "cobrahead",
  "mambahead",
  "rattlehead",
  "adderhead",
  "taipanhead",
  "kraithead",
  "seahead",
  "tuatara",
  "rhynchocephalia",
  "amphisbaenia",
  "wormlizard",
  "amphisbaenian",
  "dibamidae",
  "dibamus",
  "blindskink",
  "legless",
  "slowlizard",
  "shark",
  "whale",
  "dolphin",
  "orca",
  "porpoise",
  "seal",
  "sealion",
  "walrus",
  "manatee",
  "dugong",
  "octopus",
  "squid",
  "cuttlefish",
  "nautilus",
  "jellyfish",
  "anemone",
  "coral",
  "seahorse",
  "pipefish",
  "starfish",
  "seastar",
  "urchin",
  "sanddollar",
  "brittlefish",
  "featherstar",
  "crinoid",
  "clam",
  "oyster",
  "mussel",
  "scallop",
  "cockle",
  "conch",
  "abalone",
  "limpet",
  "snail",
  "slug",
  "nudibranch",
  "whelk",
  "periwinkle",
  "chiton",
  "crab",
  "lobster",
  "crayfish",
  "shrimp",
  "prawn",
  "krill",
  "barnacle",
  "copepod",
  "isopod",
  "amphipod",
  "eel",
  "moray",
  "conger",
  "lamprey",
  "hagfish",
  "anchovy",
  "sardine",
  "herring",
  "mackerel",
  "tuna",
  "bonito",
  "marlin",
  "sailfish",
  "swordfish",
  "barracuda",
  "grouper",
  "snapper",
  "bass",
  "cod",
  "haddock",
  "pollock",
  "whiting",
  "halibut",
  "flounder",
  "sole",
  "plaice",
  "turbot",
  "brill",
  "skate",
  "ray",
  "stingray",
  "mantaray",
  "eagleray",
  "guitarfish",
  "sawfish",
  "chimaera",
  "ratfish",
  "dogfish",
  "catshark",
  "hammerhead",
  "thresher",
  "whitetip",
  "blacktip",
  "tigerfish",
  "reefshark",
  "bullshark",
  "sandshark",
  "nurseshark",
  "megashark",
  "greenshark",
  "pufferfish",
  "blowfish",
  "porcupinefish",
  "triggerfish",
  "boxfish",
  "filefish",
  "lionfish",
  "stonefish",
  "scorpionfish",
  "rockfish",
  "clownfish",
  "damselfish",
  "angelfish",
  "butterflyfish",
  "wrasse",
  "parrotfish",
  "surgeonfish",
  "tang",
  "rabbitfish",
  "moorishidol",
  "goby",
  "blenny",
  "dragonet",
  "mudskipper",
  "remora",
  "pilotfish",
  "trevally",
  "jackfish",
  "amberjack",
  "pomfret",
  "barramundi",
  "grouperfish",
  "tilefish",
  "hogfish",
  "sheepshead",
  "drumfish",
  "croaker",
  "weakfish",
  "kingfish",
  "queenfish",
  "seabream",
  "porgy",
  "gruntfish",
  "trigger",
  "file",
  "box",
  "puffer",
  "sunfish",
  "mola",
  "opah",
  "flyingfish",
  "halfbeak",
  "needlefish",
  "garfish",
  "saury",
  "lanternfish",
  "hatchetfish",
  "dragonfish",
  "viperfish",
  "fangtooth",
  "anglerfish",
  "frogfish",
  "batfish",
  "tripodfish",
  "cusk",
  "broto",
  "eelcatfish",
  "seaangel",
  "seabutterfly",
  "salp",
  "tunicate",
  "ascidian",
  "pyrosome",
  "doliolid",
  "sponge",
  "glasssponge",
  "barrelsponge",
  "seafan",
  "seapen",
  "gorgonian",
  "zooplankton",
  "phytoplankton",
  "copepods",
  "krillfish",
  "seacucumber",
  "holothurian",
  "seapig",
  "seaslug",
  "sealamprey",
  "seaworm",
  "lugworm",
  "bristleworm",
  "bobbitworm",
  "polychaete",
  "flatworm",
  "ribbonworm",
  "nemertean",
  "arrowworm",
  "peanutworm",
  "sipunculan",
  "horseshoecrab",
  "kingcrab",
  "snowcrab",
  "spidercrab",
  "hermitcrab",
  "fiddlercrab",
  "ghostcrab",
  "bluecrab",
  "dungeness",
  "stonecrab",
  "ant",
  "termite",
  "bee",
  "honeybee",
  "bumblebee",
  "wasp",
  "hornet",
  "yellowjacket",
  "paperwasp",
  "muddauber",
  "beetle",
  "ladybug",
  "ladybird",
  "firefly",
  "lightningbug",
  "scarab",
  "stagbeetle",
  "dungbeetle",
  "clickbeetle",
  "groundbeetle",
  "butterfly",
  "monarch",
  "swallowtail",
  "admiral",
  "paintedlady",
  "fritillary",
  "hairstreak",
  "bluebutterfly",
  "skipper",
  "apollo",
  "moth",
  "silkworm",
  "hawkmoth",
  "sphinxmoth",
  "lunamoth",
  "atlasmoth",
  "polyphemus",
  "cecropia",
  "clothesmoth",
  "mealworm",
  "fly",
  "housefly",
  "fruitfly",
  "blowfly",
  "horsefly",
  "deerfly",
  "tsetse",
  "botfly",
  "crane fly",
  "hoverfly",
  "mosquito",
  "anopheles",
  "aedes",
  "culex",
  "gnat",
  "midge",
  "blackfly",
  "sandfly",
  "noseeum",
  "chironomid",
  "roach",
  "cockroach",
  "germanroach",
  "americanroach",
  "orientalroach",
  "woodroach",
  "smokybrown",
  "brownbanded",
  "surinam",
  "palmetto",
  "grasshopper",
  "locust",
  "katydid",
  "cricket",
  "fieldcricket",
  "housecricket",
  "molecricket",
  "camelcricket",
  "treecricket",
  "jerusalem",
  "mantis",
  "prayingmantis",
  "mantid",
  "mantodea",
  "stickinsect",
  "leafinsect",
  "walkingstick",
  "phasmatid",
  "spinyphasmid",
  "ghostmantis",
  "dragonfly",
  "damselfly",
  "clubtail",
  "skimmer",
  "darner",
  "emerald",
  "bluetail",
  "spreadwing",
  "jewelwing",
  "rivercruiser",
  "cicada",
  "periodicalcicada",
  "annualcicada",
  "leafhopper",
  "planthopper",
  "treehopper",
  "froghopper",
  "spittlebug",
  "lanternfly",
  "sharpshooter",
  "aphid",
  "greenfly",
  "blackflyaphid",
  "mealybug",
  "scaleinsect",
  "whitefly",
  "psyllid",
  "adelgid",
  "phylloxera",
  "cochineal",
  "bug",
  "stinkbug",
  "shieldbug",
  "bedbug",
  "kissingbug",
  "assassinbug",
  "leafbug",
  "waterbug",
  "backswimmer",
  "giantwaterbug",
  "louse",
  "headlouse",
  "bodylouse",
  "crablouse",
  "booklouse",
  "barklouse",
  "psocid",
  "trogiid",
  "liposcelid",
  "embiid",
  "thrips",
  "thysanopteran",
  "gladiatorthrips",
  "flowerthrips",
  "onionthrips",
  "westernthrips",
  "cerealthrips",
  "pearthrips",
  "chillithrips",
  "banana thrips",
  "earwig",
  "forceps",
  "europeanearwig",
  "ringlegged",
  "stripedearwig",
  "maritimeearwig",
  "tropicalearwig",
  "diplatyid",
  "spongiphorid",
  "forficulid",
  "flea",
  "catflea",
  "dogflea",
  "humanflea",
  "ratflea",
  "sandflea",
  "chigoe",
  "sticktight",
  "henflea",
  "mouseflea",
  "silverfish",
  "firebrat",
  "thermobia",
  "lepisma",
  "ctenolepisma",
  "bristletail",
  "jumpingbristletail",
  "archeognatha",
  "microcoryphia",
  "zento",
  "mayfly",
  "stonefly",
  "caddisfly",
  "alderfly",
  "dobsonfly",
  "fishfly",
  "snakefly",
  "lacewing",
  "greenlacewing",
  "brownlacewing",
  "antlion",
  "owlfly",
  "mantispid",
  "dustywings",
  "spongillafly",
  "beadedlacewing",
  "coniferaphidfly",
  "ithonid",
  "osmylid",
  "berothid",
  "weevil",
  "snoutbeetle",
  "bollweevil",
  "riceweevil",
  "granaryweevil",
  "palmweevil",
  "acornweevil",
  "vineweevil",
  "rootweevil",
  "billbug",
  "longhornbeetle",
  "capricorn",
  "sawyer",
  "cerambycid",
  "roundheaded",
  "flatheaded",
  "jewelbeetle",
  "metallicbeetle",
  "borer",
  "woodborer",
  "leafbeetle",
  "flea beetle",
  "tortoisebeetle",
  "chrysomelid",
  "galerucid",
  "alticine",
  "cassidine",
  "hispine",
  "donaciine",
  "eumolpine",
];
const colors = [
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "pink",
  "brown",
  "black",
  "white",
  "gray",
  "grey",
  "cyan",
  "magenta",
  "teal",
  "navy",
  "lime",
  "olive",
  "maroon",
  "aqua",
  "silver",
  "gold",
  "beige",
  "ivory",
  "cream",
  "tan",
  "khaki",
  "peach",
  "coral",
  "salmon",
  "turquoise",
  "mint",
  "emerald",
  "jade",
  "forest",
  "chartreuse",
  "spring",
  "seafoam",
  "aquamarine",
  "cerulean",
  "sky",
  "azure",
  "cobalt",
  "denim",
  "indigo",
  "violet",
  "plum",
  "lavender",
  "lilac",
  "orchid",
  "fuchsia",
  "raspberry",
  "crimson",
  "scarlet",
  "ruby",
  "wine",
  "burgundy",
  "brick",
  "rose",
  "blush",
  "mahogany",
  "chestnut",
  "sienna",
  "umber",
  "copper",
  "bronze",
  "brass",
  "rust",
  "terracotta",
  "clay",
  "ochre",
  "mustard",
  "amber",
  "honey",
  "butter",
  "lemon",
  "banana",
  "sunflower",
  "goldenrod",
  "sand",
  "stone",
  "slate",
  "charcoal",
  "ash",
  "smoke",
  "fog",
  "mist",
  "cloud",
  "pearl",
  "snow",
  "ice",
  "frost",
  "glacier",
  "steel",
  "iron",
  "graphite",
  "gunmetal",
  "platinum",
  "aluminum",
  "chrome",
  "midnight",
  "obsidian",
  "ink",
  "coal",
  "ebony",
  "jet",
  "onyx",
  "pitch",
  "shadow",
  "void",
  "neonred",
  "neonblue",
  "neongreen",
  "neonyellow",
  "neonpink",
  "neonorange",
  "neonpurple",
  "neoncyan",
  "neonlime",
  "neonteal",
  "pastelred",
  "pastelblue",
  "pastelgreen",
  "pastelyellow",
  "pastelpink",
  "pastelpurple",
  "pastelorange",
  "pastelteal",
  "pastelcyan",
  "pastellime",
  "darkred",
  "darkblue",
  "darkgreen",
  "darkyellow",
  "darkorange",
  "darkpurple",
  "darkpink",
  "darkbrown",
  "darkgray",
  "darkcyan",
  "lightred",
  "lightblue",
  "lightgreen",
  "lightyellow",
  "lightorange",
  "lightpurple",
  "lightpink",
  "lightbrown",
  "lightgray",
  "lightcyan",
  "softred",
  "softblue",
  "softgreen",
  "softyellow",
  "softorange",
  "softpurple",
  "softpink",
  "softbrown",
  "softgray",
  "softcyan",
  "deepred",
  "deepblue",
  "deepgreen",
  "deepyellow",
  "deeporange",
  "deeppurple",
  "deeppink",
  "deepbrown",
  "deepgray",
  "deepcyan",
  "coolred",
  "coolblue",
  "coolgreen",
  "coolyellow",
  "coolorange",
  "coolpurple",
  "coolpink",
  "coolbrown",
  "coolgray",
  "coolcyan",
  "warmred",
  "warmblue",
  "warmgreen",
  "warmyellow",
  "warmorange",
  "warmpurple",
  "warmpink",
  "warmbrown",
  "warmgray",
  "warmcyan",
  "apple",
  "pear",
  "limegreen",
  "mintgreen",
  "pinegreen",
  "mossgreen",
  "fern",
  "basil",
  "avocado",
  "celery",
  "ocean",
  "lagoon",
  "reef",
  "wave",
  "tidal",
  "deepsea",
  "pacific",
  "atlantic",
  "arctic",
  "tropical",
  "cherry",
  "strawberry",
  "watermelon",
  "cranberry",
  "pomegranate",
  "tomato",
  "paprika",
  "cayenne",
  "chili",
  "pepper",
  "grape",
  "eggplant",
  "aubergine",
  "plumdark",
  "fig",
  "mulberry",
  "boysenberry",
  "blackberry",
  "blueberry",
  "currant",
  "caramel",
  "toffee",
  "fudge",
  "mocha",
  "coffee",
  "espresso",
  "latte",
  "cappuccino",
  "chocolate",
  "cocoa",
  "vanilla",
  "custard",
  "pudding",
  "nougat",
  "almond",
  "hazelnut",
  "walnut",
  "pecan",
  "peanut",
  "cashew",
  "cotton",
  "linen",
  "silk",
  "wool",
  "canvas",
  "parchment",
  "paper",
  "bone",
  "shell",
  "chalk",
];
const cars = [
  "toyota",
  "honda",
  "ford",
  "chevrolet",
  "bmw",
  "mercedes",
  "audi",
  "volkswagen",
  "tesla",
  "nissan",
  "hyundai",
  "kia",
  "mazda",
  "subaru",
  "lexus",
  "acura",
  "infiniti",
  "volvo",
  "jaguar",
  "landrover",
  "porsche",
  "ferrari",
  "lamborghini",
  "maserati",
  "bentley",
  "rollsroyce",
  "astonmartin",
  "mclaren",
  "bugatti",
  "pagani",
  "mitsubishi",
  "suzuki",
  "isuzu",
  "daihatsu",
  "scion",
  "genesis",
  "ram",
  "gmc",
  "cadillac",
  "buick",
  "lincoln",
  "chrysler",
  "dodge",
  "jeep",
  "pontiac",
  "saturn",
  "oldsmobile",
  "hummer",
  "plymouth",
  "mercury",
  "fiat",
  "alfaRomeo",
  "lancia",
  "abarth",
  "peugeot",
  "renault",
  "citroen",
  "ds",
  "opel",
  "vauxhall",
  "seat",
  "skoda",
  "dacia",
  "cupra",
  "saab",
  "polestar",
  "smart",
  "mini",
  "mg",
  "rover",
  "geely",
  "byd",
  "chery",
  "greatwall",
  "haval",
  "wuling",
  "baojun",
  "hongqi",
  "nio",
  "xpeng",
  "li",
  "zeekr",
  "lynkco",
  "maxus",
  "foton",
  "gac",
  "saic",
  "dongfeng",
  "changan",
  "haima",
  "tata",
  "mahindra",
  "maruti",
  "force",
  "hindustan",
  "lada",
  "gaz",
  "uaz",
  "moskvich",
  "proton",
  "perodua",
  "holden",
  "koenigsegg",
  "rimac",
  "ssc",
  "zenvo",
  "lucid",
  "rivian",
  "fisker",
  "faradayfuture",
  "karma",
  "canoo",
  "vinfast",
  "pagani",
  "ariel",
  "noble",
  "lotus",
  "tvr",
];
const jobs = [
  "teacher",
  "engineer",
  "doctor",
  "nurse",
  "lawyer",
  "developer",
  "programmer",
  "designer",
  "manager",
  "director",
  "accountant",
  "auditor",
  "analyst",
  "consultant",
  "architect",
  "scientist",
  "researcher",
  "technician",
  "operator",
  "mechanic",
  "electrician",
  "plumber",
  "carpenter",
  "welder",
  "painter",
  "roofer",
  "mason",
  "bricklayer",
  "contractor",
  "builder",
  "chef",
  "cook",
  "baker",
  "butcher",
  "barista",
  "bartender",
  "waiter",
  "waitress",
  "server",
  "host",
  "cashier",
  "clerk",
  "receptionist",
  "assistant",
  "secretary",
  "administrator",
  "coordinator",
  "scheduler",
  "planner",
  "organizer",
  "salesperson",
  "salesman",
  "saleswoman",
  "marketer",
  "advertiser",
  "promoter",
  "strategist",
  "copywriter",
  "contentcreator",
  "editor",
  "writer",
  "author",
  "journalist",
  "reporter",
  "columnist",
  "blogger",
  "publisher",
  "proofreader",
  "critic",
  "reviewer",
  "photographer",
  "videographer",
  "filmmaker",
  "producer",
  "directorfilm",
  "actor",
  "actress",
  "voiceactor",
  "stuntman",
  "extra",
  "musician",
  "singer",
  "songwriter",
  "composer",
  "conductor",
  "dj",
  "rapper",
  "guitarist",
  "pianist",
  "drummer",
  "artist",
  "illustrator",
  "painterartist",
  "sculptor",
  "animator",
  "motiondesigner",
  "modeler",
  "conceptartist",
  "tattooist",
  "calligrapher",
  "dentist",
  "orthodontist",
  "surgeon",
  "anesthesiologist",
  "radiologist",
  "pathologist",
  "pharmacist",
  "optometrist",
  "therapist",
  "psychologist",
  "psychiatrist",
  "counselor",
  "socialworker",
  "caregiver",
  "caretaker",
  "nanny",
  "babysitter",
  "midwife",
  "doula",
  "paramedic",
  "firefighter",
  "police",
  "detective",
  "investigator",
  "sheriff",
  "marshal",
  "constable",
  "guard",
  "bodyguard",
  "bouncer",
  "soldier",
  "officer",
  "commander",
  "general",
  "veteran",
  "strategistmilitary",
  "intelligence",
  "cryptanalyst",
  "logistician",
  "quartermaster",
  "pilot",
  "copilot",
  "flightattendant",
  "airtraffic",
  "dispatcher",
  "navigator",
  "engineerflight",
  "technicianflight",
  "aeronaut",
  "astronaut",
  "driver",
  "chauffeur",
  "trucker",
  "delivery",
  "courier",
  "messenger",
  "rider",
  "dispatchertransport",
  "conductorrail",
  "engineerrail",
  "captain",
  "sailor",
  "seaman",
  "deckhand",
  "boatswain",
  "harbormaster",
  "fisherman",
  "angler",
  "diver",
  "marinebiologist",
  "farmer",
  "rancher",
  "herdsman",
  "shepherd",
  "dairyman",
  "beekeeper",
  "horticulturist",
  "florist",
  "gardener",
  "landscaper",
  "agronomist",
  "soilscientist",
  "cropmanager",
  "irrigator",
  "harvester",
  "tractorist",
  "greenkeeper",
  "groundskeeper",
  "arborist",
  "forester",
  "economist",
  "statistician",
  "mathematician",
  "actuary",
  "quant",
  "riskmanager",
  "underwriter",
  "broker",
  "trader",
  "investor",
  "banker",
  "teller",
  "loanofficer",
  "creditanalyst",
  "mortgage",
  "financier",
  "treasurer",
  "controller",
  "bookkeeper",
  "payroll",
  "recruiter",
  "headhunter",
  "hrmanager",
  "trainer",
  "coach",
  "mentor",
  "facilitator",
  "mediator",
  "negotiator",
  "arbitrator",
  "professor",
  "lecturer",
  "instructor",
  "educator",
  "tutor",
  "teacherassistant",
  "principal",
  "dean",
  "chancellor",
  "superintendent",
  "librarian",
  "archivist",
  "curator",
  "historian",
  "anthropologist",
  "sociologist",
  "politicalscientist",
  "geographer",
  "demographer",
  "ethnographer",
];
const books = [
  "to kill a mockingbird",
  "pride and prejudice",
  "the catcher in the rye",
  "the great gatsby",
  "lord of the flies",
  "animal farm",
  "of mice and men",
  "the old man and the sea",
  "catch 22",
  "one hundred years of solitude",
  "the road",
  "the bell jar",
  "slaughterhouse five",
  "the picture of dorian gray",
  "gone with the wind",
  "the sun also rises",
  "white teeth",
  "the handmaids tale",
  "a farewell to arms",
  "the book thief",
  "life of pi",
  "the kite runner",
  "the secret history",
  "the time traveler’s wife",
  "the namesake",
  "americanah",
  "midnight’s children",
  "the luminosity of stars",
  "the shadow of the wind",
  "the goldfinch",
  "the night circus",
  "the underground railroad",
  "everything is illuminates",
  "the little friend",
  "the lovely bones",
  "everything i never told you",
  "the girl on the train",
  "the nightingale",
  "the alice network",
  "all the light we cannot see",
  "the seven husbands of evelyn hugo",
  "the great alone",
  "before we were strangers",
  "where the crawdads sing",
  "the paris library",
  "the midnight library",
  "lessons in chemistry",
  "the house in the cerulean sea",
  "the book of lost things",
  "the story of edgar sawtelle",
  "the ocean at the end of the lane",
  "the history of bees",
  "the sea of tranquility",
  "the power",
  "the giver of stars",
  "the institute",
  "the girl with seven names",
  "the shadow king",
  "the art of hearing heartbeats",
  "the winter king",
  "the rose code",
  "the only plane in the sky",
  "the last thing he told me",
  "the book woman of trouble creek",
  "the paris library",
  "the personal librarian",
  "the vanished birds",
  "the forest of vanishing stars",
  "the lost apothecary",
  "the postmistress",
  "the violet hour",
  "the jeweler’s wife",
  "the yellow house",
  "the baker’s secret",
  "the piano shop on the left bank",
  "the third wife",
  "the house of the spirits",
  "the joy luck club",
  "the kitchen house",
  "the memory keeper’s daughter",
  "the light between oceans",
  "the golden house",
  "the last narrative",
  "the city of mirrors",
  "the heart’s invisible furies",
  "the water dancer",
  "the stars are fire",
  "the dreamers",
  "the night watchman",
  "the weight of ink",
  "the twelve lives of samuel hawley",
  "the house of spirits",
  "the man who loved books too much",
  "the gospel of the knife",
  "the lost vintage",
  "the thirteen clocks",
  "the firekeeper saga",
  "the wandering earth",
  "harry potter and the philosophers stone",
  "harry potter and the chamber of secrets",
  "harry potter and the prisoner of azkaban",
  "harry potter and the goblet of fire",
  "harry potter and the order of the phoenix",
  "harry potter and the half blood prince",
  "harry potter and the deathly hallows",
  "the hobbit",
  "the fellowship of the ring",
  "the two towers",
  "the return of the king",
  "the lion the witch and the wardrobe",
  "prince caspian",
  "the voyage of the dawn treader",
  "the silver chair",
  "the horse and his boy",
  "the magician’s nephew",
  "the last battle",
  "a game of thrones",
  "a clash of kings",
  "a storm of swords",
  "a feast for crows",
  "a dance with dragons",
  "the name of the wind",
  "the wise mans fear",
  "the doors of stone",
  "the way of kings",
  "words of radiance",
  "oathbringer",
  "rhythm of war",
  "the black prism",
  "the blinding knife",
  "the broken eye",
  "the blood mirror",
  "the burning white",
  "the wheel of time eye of the world",
  "the great hunt",
  "the dragon reborn",
  "the shadow rising",
  "the fires of heaven",
  "lord of chaos",
  "a crown of swords",
  "the path of daggers",
  "winter’s heart",
  "crossroads of twilight",
  "knife of dreams",
  "the gathering storm",
  "towers of midnight",
  "a memory of light",
  "the lightning thief",
  "sea of monsters",
  "the titan’s curse",
  "the battle of the labyrinth",
  "the last olympian",
  "percy jackson and the olympians",
  "heroes of olympus",
  "magnus chase",
  "the trials of apollo",
  "the dark is rising",
  "greenwitch",
  "blue witch",
  "the grey king",
  "silver on the tree",
  "earthsea the wizard of earthsea",
  "the tombs of atuan",
  "the farthest shore",
  "tehanu",
  "tales from earthsea",
  "the other wind",
  "the golden compass",
  "the subtle knife",
  "the amber spyglass",
  "the lie of locke lamora",
  "red seas under red skies",
  "the republic of thieves",
  "mistborn the final empire",
  "the well of ascension",
  "the hero of ages",
  "the alloy of law",
  "shadows of self",
  "the bands of mourning",
  "elantris",
  "warbreaker",
  "dune",
  "neuromancer",
  "ender’s game",
  "foundation",
  "snow crash",
  "ready player one",
  "the martian",
  "the hunger games",
  "catching fire",
  "mockingjay",
  "the time machine",
  "the war of the worlds",
  "fahrenheit 451",
  "1984",
  "brave new world",
  "the left hand of darkness",
  "hyperion",
  "the moon is a harsh mistress",
  "childhood’s end",
  "starship troopers",
  "the forever war",
  "old mans war",
  "altered carbon",
  "the expanse leviathan wakes",
  "the expanse caliban’s war",
  "the expanse abaddon’s gate",
  "the expanse cibola burn",
  "the expanse nemesis games",
  "the expanse babylon’s ashes",
  "the expanse persepolis rising",
  "the expanse tleilax’s dawn",
  "ready player two",
  "foundation and empire",
  "second foundation",
  "robots of dawn",
  "i robot",
  "caves of steel",
  "nemesis",
  "ringworld",
  "the integral trees",
  "the smoke ring",
  "red mars",
  "green mars",
  "blue mars",
  "the martian chronicles",
  "fountains of paradise",
  "contact",
  "childhood’s end",
  "ringworld engineers",
  "speaker for the dead",
  "xenocide",
  "children of the mind",
  "the moon era",
  "think and grow rich",
  "how to win friends and influence people",
  "the 7 habits of highly effective people",
  "rich dad poor dad",
  "the power of positive thinking",
  "the secret",
  "awaken the giant within",
  "you are a badass",
  "the magic of thinking big",
  "the subtle art of not giving a f",
  "the millionaire next door",
  "the one thing",
  "the 48 laws of power",
  "the compound effect",
  "the magic of thinking big",
  "the power of habit",
  "atomic habits",
  "get rich slow",
  "deep work",
  "essentialism",
  "drive",
  "mindset",
  "grit",
  "outliers",
  "start with why",
  "daring greatly",
  "man’s search for meaning",
  "the four agreements",
  "the 5 am club",
  "the war of art",
  "principles",
  "tools of titans",
  "never split the difference",
  "crushing it",
  "purple cow",
  "good to great",
  "built to last",
  "zero to one",
  "elon musk biography",
  "steve jobs biography",
  "the art of war",
  "the art of happiness",
  "flow",
  "the happiness advantage",
  "the road less traveled",
  "the monk who sold his ferrari",
  "rich dad guide to investing",
  "the lean startup",
  "the personal MBA",
  "the power of now",
  "the subtle art of not giving a f",
  "the slight edge",
  "the success principles",
  "the leader who had no title",
  "the millionaire mind",
  "the wealth of nations",
  "how to stop worrying and start living",
  "winning",
  "the 10x rule",
  "high performance habits",
  "principles of success",
  "the richest man in babylon",
  "your money or your life",
  "the law of attraction",
  "think like a monk",
  "i will teach you to be rich",
  "the alchemist",
  "the courage to be disliked",
  "the success system that never fails",
  "mastery",
  "the psychology of money",
  "the dip",
  "the millionaire fastlane",
  "the power of focus",
  "the magic of belief",
  "the power of intention",
  "rich dad guide to finances",
  "the laws of success",
  "the success habits",
  "millionaire mind intensive",
  "the ultimate sales machine",
  "the productivity project",
  "the happiness project",
  "the confidence code",
  "the art of possibility",
  "getting things done",
  "the talent code",
  "the book of joy",
  "the magic of gratitude",
  "the path to wealth",
  "the abundance mindset",
  "the wealth mindset",
  "the keys to success",
];
const cities = [
  "new york",
  "los angeles",
  "chicago",
  "houston",
  "phoenix",
  "philadelphia",
  "san antonio",
  "san diego",
  "dallas",
  "san jose",
  "austin",
  "jacksonville",
  "fort worth",
  "columbus",
  "charlotte",
  "san francisco",
  "indianapolis",
  "seattle",
  "denver",
  "washington",
  "boston",
  "el paso",
  "nashville",
  "detroit",
  "oklahoma city",
  "portland",
  "las vegas",
  "memphis",
  "louisville",
  "baltimore",
  "milwaukee",
  "albuquerque",
  "tucson",
  "fresno",
  "sacramento",
  "kansas city",
  "long beach",
  "mesa",
  "atlanta",
  "colorado springs",
  "virginia beach",
  "raleigh",
  "omaha",
  "miami",
  "oakland",
  "minneapolis",
  "tulsa",
  "wichita",
  "new orleans",
  "arlington",
  "cleveland",
  "bakersfield",
  "tampa",
  "aurora",
  "honolulu",
  "anaheim",
  "santa ana",
  "corpus christi",
  "riverside",
  "lexington",
  "st louis",
  "stockton",
  "pittsburgh",
  "saint paul",
  "cincinnati",
  "anchorage",
  "henderson",
  "greensboro",
  "plano",
  "newark",
  "toledo",
  "lincoln",
  "orlando",
  "jersey city",
  "chula vista",
  "fort wayne",
  "buffalo",
  "durham",
  "st. petersburg",
  "laredo",
  "irving",
  "garland",
  "chandler",
  "madison",
  "lubbock",
  "scottsdale",
  "reno",
  "glendale",
  "norfolk",
  "winston salem",
  "north las vegas",
  "irvine",
  "chesapeake",
  "gilbert",
  "hialeah",
  "fremont",
  "boise",
  "birmingham",
  "spokane",
  "rochester",
  "des moines",
  "modesto",
  "fayetteville",
  "tacoma",
  "oxnard",
  "fontana",
  "columbia",
  "moreno valley",
  "popular city 101",
  "montreal",
  "toronto",
  "vancouver",
  "calgary",
  "edmonton",
  "ottawa",
  "winnipeg",
  "quebec city",
  "hamilton",
  "kitchener",
  "halifax",
  "victoria",
  "saskatoon",
  "regina",
  "st. john’s",
  "windsor",
  "surrey",
  "burlington",
  "markham",
  "longueuil",
  "burnaby",
  "richmond",
  "gatineau",
  "santa fe",
  "mexico city",
  "guadalajara",
  "monterrey",
  "puebla",
  "tijuana",
  "leon",
  "juarez",
  "zapopan",
  "san luis potosi",
  "queretaro",
  "mexicali",
  "ciudad victoria",
  "tuxtla gutierrez",
  "cancun",
  "merida",
  "toluca",
  "veracruz",
  "toluca de lerdo",
  "morelia",
  "coatzacoalcos",
  "aguascalientes",
  "chilpancingo",
  "zacatecas",
  "san cristobal de las casas",
  "manzanillo",
  "acapulco",
  "mazatlan",
  "nuevo laredo",
  "matamoros",
  "reynosa",
  "popular city 102",
  "nassau",
  "kingston",
  "havana",
  "guatemala city",
  "belize city",
  "san salvador",
  "tegucigalpa",
  "managua",
  "panama city",
  "san jose costa rica",
  "san juan",
  "bridgetown",
  "port au prince",
  "georgetown",
  "roseau",
  "st. george's",
  "kingston jamaica",
  "cockburn town",
  "governors harbour",
  "fredericton",
  "halifax canada",
  "st. john's canada",
  "sao paulo",
  "rio de janeiro",
  "brasilia",
  "salvador",
  "fortaleza",
  "belo horizonte",
  "manaus",
  "curitiba",
  "recife",
  "porto alegre",
  "belem",
  "goiania",
  "guarulhos",
  "campinas",
  "nova iguacu",
  "sao luis",
  "sao bernardo do campo",
  "santo andre",
  "teresina",
  "cuiaba",
  "joao pessoa",
  "joinville",
  "ribeirao preto",
  "natal",
  "maceio",
  "duque de caxias",
  "campo grande",
  "osasco",
  "santo andre",
  "santos",
  "aracaju",
  "sergipe",
  "franca",
  "petropolis",
  "macapa",
  "vitoria",
  "caxias do sul",
  "pelotas",
  "caruaru",
  "volta redonda",
  "itabuna",
  "joao pessoa",
  "buenos aires",
  "cordoba",
  "rosario",
  "mendoza",
  "la plata",
  "san miguel de tucuman",
  "mar del plata",
  "salta",
  "resistencia",
  "santa fe",
  "corrientes",
  "posadas",
  "san juan",
  "parana",
  "neuquen",
  "san salvador de jujuy",
  "rio cuarto",
  "cipolletti",
  "formosa",
  "rio gallegos",
  "bogota",
  "medellin",
  "cali",
  "barranquilla",
  "cartagena",
  "cucuta",
  "soledad",
  "bucaramanga",
  "pereira",
  "valledupar",
  "ibague",
  "manizales",
  "barrancabermeja",
  "monteria",
  "sincelejo",
  "neiva",
  "popayan",
  "pasto",
  "villavicencio",
  "tunja",
  "santiago",
  "valparaiso",
  "concepcion",
  "la serena",
  "antofagasta",
  "temuco",
  "iquique",
  "puerto montt",
  "rancagua",
  "arica",
  "talca",
  "chillan",
  "los angeles",
  "osorno",
  "valdivia",
  "copiapo",
  "quillota",
  "curico",
  "san antonio",
  "ancud",
  "lima",
  "arequipa",
  "trujillo",
  "chiclayo",
  "piura",
  "cusco",
  "huancayo",
  "puno",
  "iquitos",
  "chimbote",
  "talara",
  "tacna",
  "moquegua",
  "pucallpa",
  "sullana",
  "huanuco",
  "piura",
  "ayacucho",
  "jaen",
  "tarapoto",
  "caracas",
  "maracaibo",
  "valencia",
  "barquisimeto",
  "ciudad guayana",
  "puerto la cruz",
  "puerto ordaz",
  "merida",
  "ciudad bolivar",
  "maracay",
  "san cristobal",
  "maturin",
  "barinas",
  "coro",
  "puerto ayacucho",
  "guanare",
  "valera",
  "carupano",
  "la guaira",
  "upata",
  "quito",
  "guayaquil",
  "cuenca",
  "santo domingo",
  "machala",
  "manta",
  "portoviejo",
  "esmeraldas",
  "loja",
  "riobamba",
  "babahoyo",
  "tulcan",
  "ambato",
  "iquitos",
  "latacunga",
  "salinas",
  "playas",
  "milagro",
  "azogues",
  "riobamba",
  "la paz",
  "santa cruz de la sierra",
  "cochabamba",
  "el alto",
  "sucre",
  "oruro",
  "potosi",
  "tarija",
  "trinidad",
  "santa ana",
  "montero",
  "quillacollo",
  "samaipata",
  "camiri",
  "yacuiba",
  "bermejo",
  "warnes",
  "san borja",
  "guayaramerin",
  "riberalta",
  "montevideo",
  "salto",
  "punta del este",
  "rivera",
  "maldonado",
  "tranqueras",
  "tacuarembo",
  "minas",
  "durazno",
  "rocha",
  "asuncion",
  "ciudad del este",
  "encarnacion",
  "luque",
  "san lorenzo",
  "capiata",
  "lambaré",
  "villarrica",
  "caaguazu",
  "coronel oviedo",
  "georgetown",
  "paramaribo",
  "cayenne",
  "beijing",
  "shanghai",
  "guangzhou",
  "shenzhen",
  "tianjin",
  "chongqing",
  "chengdu",
  "wuhan",
  "hong kong",
  "hangzhou",
  "suzhou",
  "nanjing",
  "shenyang",
  "qingdao",
  "dalian",
  "jinan",
  "xian",
  "fuzhou",
  "zhengzhou",
  "changsha",
  "kunming",
  "dongguan",
  "ningbo",
  "harbin",
  "taiyuan",
  "huhehaote",
  "shijiazhuang",
  "wuxi",
  "nanning",
  "haikou",
  "hainan",
  "changchun",
  "foshan",
  "dongying",
  "qingyuan",
  "zhuhai",
  "nantong",
  "zibo",
  "lanzhou",
  "xiangyang",
  "xiamen",
  "tokyo",
  "osaka",
  "nagoya",
  "sapporo",
  "fukuoka",
  "kobe",
  "kyoto",
  "kawasaki",
  "saitama",
  "hiroshima",
  "sendai",
  "kitakyushu",
  "chiba",
  "sakai",
  "shizuoka",
  "niigata",
  "hamamatsu",
  "okayama",
  "kumamoto",
  "kagoshima",
  "mumbai",
  "delhi",
  "bangalore",
  "kolkata",
  "chennai",
  "hyderabad",
  "pune",
  "ahmedabad",
  "surat",
  "jaipur",
  "lucknow",
  "kanpur",
  "nagpur",
  "indore",
  "thiruvananthapuram",
  "patna",
  "bhopal",
  "ludhiana",
  "agra",
  "nashik",
  "faridabad",
  "meerut",
  "rajkot",
  "varanasi",
  "vasai",
  "srinagar",
  "aurangabad",
  "dhanbad",
  "amritsar",
  "navi mumbai",
  "jakarta",
  "surabaya",
  "bandung",
  "medan",
  "semarang",
  "palembang",
  "makassar",
  "tangerang",
  "depok",
  "bekasi",
  "bogor",
  "padang",
  "malang",
  "solo",
  "pontianak",
  "banjarmasin",
  "balikpapan",
  "palangkaraya",
  "denpasar",
  "mataram",
  "karachi",
  "lahore",
  "faisalabad",
  "rawalpindi",
  "multan",
  "peshawar",
  "quetta",
  "islamabad",
  "sialkot",
  "gujranwala",
  "hyderabad pakistan",
  "sukkur",
  "bahawalpur",
  "mirpur khas",
  "okara",
  "sheikhupura",
  "sargodha",
  "mardan",
  "pakpattan",
  "mianwali",
  "bangkok",
  "phnom penh",
  "ho chi minh city",
  "hanoi",
  "yangon",
  "kuala lumpur",
  "singapore",
  "manila",
  "cebu",
  "davao",
  "seoul",
  "busan",
  "incheon",
  "taegu",
  "daegu",
  "gwangju",
  "pyongyang",
  "thimphu",
  "colombo",
  "male",
  "isfahan",
  "tehran",
  "dubai",
  "abu dhabi",
  "doha",
  "riyadh",
  "jeddah",
  "kuwait city",
  "muscat",
  "amman",
  "beirut",
  "damascus",
  "baghdad",
  "baku",
  "tashkent",
  "almaty",
  "astana",
  "bishkek",
  "dushanbe",
  "ashgabat",
  "yerevan",
  "tbilisi",
  "bishkek",
  "hamedan",
  "shiraz",
  "london",
  "birmingham",
  "glasgow",
  "manchester",
  "leeds",
  "liverpool",
  "sheffield",
  "edinburgh",
  "bristol",
  "leicester",
  "coventry",
  "kingston upon hull",
  "cardiff",
  "belfast",
  "stoke on trent",
  "southampton",
  "plymouth",
  "nottingham",
  "derby",
  "portsmouth",
  "newcastle upon tyne",
  "london",
  "birmingham",
  "glasgow",
  "manchester",
  "leeds",
  "liverpool",
  "sheffield",
  "edinburgh",
  "bristol",
  "leicester",
  "coventry",
  "kingston upon hull",
  "cardiff",
  "belfast",
  "stoke on trent",
  "southampton",
  "plymouth",
  "nottingham",
  "derby",
  "portsmouth",
  "newcastle upon tyne",
  "berlin",
  "hamburg",
  "munich",
  "cologne",
  "frankfurt",
  "stuttgart",
  "dusseldorf",
  "dortmund",
  "essen",
  "leipzig",
  "bremen",
  "dresden",
  "hannover",
  "nuremberg",
  "duisburg",
  "bochum",
  "wuppertal",
  "bielefeld",
  "bonn",
  "munster",
  "paris",
  "marseille",
  "lyon",
  "toulouse",
  "nice",
  "nantes",
  "strasbourg",
  "montpellier",
  "bordeaux",
  "lille",
  "rennes",
  "reims",
  "le havre",
  "saint etienne",
  "toulon",
  "grenoble",
  "dijon",
  "angers",
  "villeurbanne",
  "clermont ferrand",
  "madrid",
  "barcelona",
  "valencia",
  "sevilla",
  "zaragoza",
  "malaga",
  "murcia",
  "palma",
  "las palmas",
  "bilbao",
  "alicante",
  "cordoba",
  "valladolid",
  "vigo",
  "gijon",
  "l'hospitalet de llobregat",
  "a coruna",
  "granada",
  "vitoria gasteiz",
  "elche",
  "moscow",
  "saint petersburg",
  "novosibirsk",
  "yekaterinburg",
  "nizhny novgorod",
  "kazan",
  "chelyabinsk",
  "omsk",
  "samara",
  "rostov on don",
  "ufa",
  "krasnoyarsk",
  "perm",
  "voronezh",
  "volgograd",
  "krasnodar",
  "saratov",
  "tyumen",
  "tolyatti",
  "izhevsk",
  "warsaw",
  "krakow",
  "lodz",
  "wroclaw",
  "poznan",
  "gdansk",
  "szczecin",
  "bydgoszcz",
  "lublin",
  "bialystok",
  "katowice",
  "czestochowa",
  "radom",
  "sosnowiec",
  "torun",
  "kielce",
  "gliwice",
  "zabrze",
  "bytom",
  "olkusz",
  "amsterdam",
  "rotterdam",
  "the hague",
  "utrecht",
  "eindhoven",
  "tilburg",
  "groningen",
  "almere",
  "breda",
  "nijmegen",
  "apeldoorn",
  "haarlem",
  "arnhem",
  "zaanstad",
  "amersfoort",
  "s-Hertogenbosch",
  "haarlemmermeer",
  "zoetermeer",
  "leiden",
  "dordrecht",
  "brussels",
  "antwerp",
  "ghent",
  "charleroi",
  "bruges",
  "liege",
  "namur",
  "leuven",
  "mons",
  "mechelen",
  "aalst",
  "sint niklaas",
  "ternat",
  "kortrijk",
  "herstal",
  "verviers",
  "louvain la neuve",
  "bastogne",
  "dinant",
  "spa",
  "vienna",
  "budapest",
  "prague",
  "bratislava",
  "ljubljana",
  "zagreb",
  "sarajevo",
  "belgrade",
  "skopje",
  "tirana",
  "sofia",
  "athens",
  "thessaloniki",
  "lisbon",
  "porto",
  "barcelona",
  "valencia",
  "bilbao",
  "madrid",
  "malaga",
  "sydney",
  "melbourne",
  "brisbane",
  "perth",
  "adelaide",
  "gold coast",
  "newcastle",
  "canberra",
  "sunshine coast",
  "hobart",
  "geelong",
  "townsville",
  "cairns",
  "toowoomba",
  "darwin",
  "ballarat",
  "bendigo",
  "albury",
  "launceston",
  "mackay",
  "rockhampton",
  "bunbury",
  "coffs harbour",
  "wollongong",
  "mackay",
  "hervey bay",
  "bundaberg",
  "ballina",
  "mount gambier",
  "geraldton",
  "orange",
  "traralgon",
  "devonport",
  "port macquarie",
  "portland",
  "tamworth",
  "mount isa",
  "alice springs",
  "broome",
  "kalgoorlie",
  "mackay",
  "bundaberg",
  "warrnambool",
  "coffs harbour",
  "bunbury",
  "morwell",
  "lismore",
  "shepparton",
  "goulburn",
  "queanbeyan",
  "port hedland",
  "lagos",
  "abuja",
  "port harcourt",
  "kano",
  "ibadan",
  "kaduna",
  "benin city",
  "enugu",
  "oshogbo",
  "jos",
  "cairo",
  "alexandria",
  "giza",
  "shubra el kheima",
  "port said",
  "suez",
  "luxor",
  "aswan",
  "ismailia",
  "mansoura",
  "johannesburg",
  "cape town",
  "durban",
  "pretoria",
  "port elizabeth",
  "bloemfontein",
  "east london",
  "nelspruit",
  "kimberley",
  "pietermaritzburg",
  "nairobi",
  "mombasa",
  "kisumu",
  "nakuru",
  "eldoret",
  "thika",
  "bungoma",
  "malindi",
  "kitale",
  "machakos",
  "casablanca",
  "rabat",
  "marrakech",
  "fes",
  "tanger",
  "agadir",
  "meknes",
  "oujda",
  "kenitra",
  "safi",
];
const countries = [
  "afghanistan",
  "albania",
  "algeria",
  "andorra",
  "angola",
  "antigua and barbuda",
  "argentina",
  "armenia",
  "australia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "barbados",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bhutan",
  "bolivia",
  "bosnia and herzegovina",
  "botswana",
  "brazil",
  "brunei",
  "bulgaria",
  "burkina faso",
  "burundi",
  "cabo verde",
  "cambodia",
  "cameroon",
  "canada",
  "central african republic",
  "chad",
  "chile",
  "china",
  "colombia",
  "comoros",
  "congo",
  "democratic republic of the congo",
  "costa rica",
  "croatia",
  "cuba",
  "cyprus",
  "czech republic",
  "denmark",
  "djibouti",
  "dominica",
  "dominican republic",
  "ecuador",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "ethiopia",
  "fiji",
  "finland",
  "france",
  "gabon",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "grenada",
  "guatemala",
  "guinea",
  "guinea-bissau",
  "guyana",
  "haiti",
  "honduras",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "israel",
  "italy",
  "jamaica",
  "japan",
  "jordan",
  "kazakhstan",
  "kenya",
  "kiribati",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "madagascar",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall islands",
  "mauritania",
  "mauritius",
  "mexico",
  "micronesia",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "mozambique",
  "myanmar",
  "namibia",
  "nauru",
  "nepal",
  "netherlands",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "north korea",
  "north macedonia",
  "norway",
  "oman",
  "pakistan",
  "palau",
  "palestine",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "qatar",
  "romania",
  "russia",
  "rwanda",
  "saint kitts and nevis",
  "saint lucia",
  "saint vincent and the grenadines",
  "samoa",
  "san marino",
  "sao tome and principe",
  "saudi arabia",
  "senegal",
  "serbia",
  "seychelles",
  "sierra leone",
  "singapore",
  "slovakia",
  "slovenia",
  "solomon islands",
  "somalia",
  "south africa",
  "south korea",
  "south sudan",
  "spain",
  "sri lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "syria",
  "taiwan",
  "tajikistan",
  "tanzania",
  "thailand",
  "timor-leste",
  "togo",
  "tonga",
  "trinidad and tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "tuvalu",
  "uganda",
  "ukraine",
  "united arab emirates",
  "united kingdom",
  "united states",
  "uruguay",
  "uzbekistan",
  "vanuatu",
  "vatican city",
  "venezuela",
  "vietnam",
  "yemen",
  "zambia",
  "zimbabwe",
];

export { animals, colors, cars, jobs, books, countries, cities };
