import Z1 from "./images/Z-1.png";
import Z2 from "./images/Z-2.png";
import C02 from "./images/C-02.jpg";
import C03 from "./images/C-03.jpg";
import C04 from "./images/C-04.jpg";
import C05 from "./images/C-05.jpg";
import C06 from "./images/C-06.jpg";
import C07 from "./images/C-07.jpg";
import C08 from "./images/C-08.jpg";
import C09 from "./images/C-09.jpg";
import C10 from "./images/C-10.jpg";
import CJ from "./images/C-J.jpg";
import CQ from "./images/C-Q.jpg";
import CK from "./images/C-K.jpg";
import CA from "./images/C-A.jpg";
import D02 from "./images/D-02.jpg";
import D03 from "./images/D-03.jpg";
import D04 from "./images/D-04.jpg";
import D05 from "./images/D-05.jpg";
import D06 from "./images/D-06.jpg";
import D07 from "./images/D-07.jpg";
import D08 from "./images/D-08.jpg";
import D09 from "./images/D-09.jpg";
import D10 from "./images/D-10.jpg";
import DJ from "./images/D-J.jpg";
import DQ from "./images/D-Q.jpg";
import DK from "./images/D-K.jpg";
import DA from "./images/D-A.jpg";
import H02 from "./images/H-02.jpg";
import H03 from "./images/H-03.jpg";
import H04 from "./images/H-04.jpg";
import H05 from "./images/H-05.jpg";
import H06 from "./images/H-06.jpg";
import H07 from "./images/H-07.jpg";
import H08 from "./images/H-08.jpg";
import H09 from "./images/H-09.jpg";
import H10 from "./images/H-10.jpg";
import HJ from "./images/H-J.jpg";
import HQ from "./images/H-Q.jpg";
import HK from "./images/H-K.jpg";
import HA from "./images/H-A.jpg";
import S02 from "./images/S-02.jpg";
import S03 from "./images/S-03.jpg";
import S04 from "./images/S-04.jpg";
import S05 from "./images/S-05.jpg";
import S06 from "./images/S-06.jpg";
import S07 from "./images/S-07.jpg";
import S08 from "./images/S-08.jpg";
import S09 from "./images/S-09.jpg";
import S10 from "./images/S-10.jpg";
import SJ from "./images/S-J.jpg";
import SQ from "./images/S-Q.jpg";
import SK from "./images/S-K.jpg";
import SA from "./images/S-A.jpg";

const chips = [Z1, Z2];
const clubs = [C02, C03, C04, C05, C06, C07, C08, C09, C10, CJ, CQ, CK, CA];
const diamonds = [D02, D03, D04, D05, D06, D07, D08, D09, D10, DJ, DQ, DK, DA];
const hearts = [H02, H03, H04, H05, H06, H07, H08, H09, H10, HJ, HQ, HK, HA];
const spades = [S02, S03, S04, S05, S06, S07, S08, S09, S10, SJ, SQ, SK, SA];

export {chips, clubs, diamonds, hearts, spades};