import {bluePics, redPics} from "./imagesGroup";
import E00 from "./images/E00.jpg";

const bluePicsArray = [
    {currentLocation: -1, correctLocation: 0, image: bluePics[0], isFilled: true},
    {currentLocation: -1, correctLocation: 1, image: bluePics[1], isFilled: true},
    {currentLocation: -1, correctLocation: 2, image: bluePics[2], isFilled: true},
    {currentLocation: -1, correctLocation: 3, image: bluePics[3], isFilled: true},
    {currentLocation: -1, correctLocation: 4, image: bluePics[4], isFilled: true},
    {currentLocation: -1, correctLocation: 5, image: bluePics[5], isFilled: true},
    {currentLocation: -1, correctLocation: 6, image: bluePics[6], isFilled: true},
    {currentLocation: -1, correctLocation: 7, image: bluePics[7], isFilled: true},
    {currentLocation: -1, correctLocation: 8, image: bluePics[8], isFilled: true},
    {currentLocation: -1, correctLocation: 9, image: bluePics[9], isFilled: true},
    {currentLocation: -1, correctLocation: 10, image: bluePics[10], isFilled: true},
    {currentLocation: -1, correctLocation: 11, image: bluePics[11], isFilled: true},
    {currentLocation: -1, correctLocation: 12, image: bluePics[12], isFilled: true},
    {currentLocation: -1, correctLocation: 13, image: bluePics[13], isFilled: true},
    {currentLocation: -1, correctLocation: 14, image: bluePics[14], isFilled: true},
    {currentLocation: -1, correctLocation: 15, image: bluePics[15], isFilled: true},
    {currentLocation: -1, correctLocation: 16, image: bluePics[16], isFilled: true},
    {currentLocation: -1, correctLocation: 17, image: bluePics[17], isFilled: true},
    {currentLocation: -1, correctLocation: 18, image: bluePics[18], isFilled: true},
    {currentLocation: -1, correctLocation: 19, image: bluePics[19], isFilled: true},
    {currentLocation: -1, correctLocation: 20, image: bluePics[20], isFilled: true},
    {currentLocation: -1, correctLocation: 21, image: bluePics[21], isFilled: true},
    {currentLocation: -1, correctLocation: 22, image: bluePics[22], isFilled: true},
    {currentLocation: -1, correctLocation: 23, image: bluePics[23], isFilled: true},
    {currentLocation: -1, correctLocation: 24, image: bluePics[24], isFilled: true},
    {currentLocation: -1, correctLocation: 25, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 26, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 27, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 28, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 29, image: E00, isFilled: true}
];

const redPicsArray = [
    {currentLocation: -1, correctLocation: 0, image: redPics[0], isFilled: true},
    {currentLocation: -1, correctLocation: 1, image: redPics[1], isFilled: true},
    {currentLocation: -1, correctLocation: 2, image: redPics[2], isFilled: true},
    {currentLocation: -1, correctLocation: 3, image: redPics[3], isFilled: true},
    {currentLocation: -1, correctLocation: 4, image: redPics[4], isFilled: true},
    {currentLocation: -1, correctLocation: 5, image: redPics[5], isFilled: true},
    {currentLocation: -1, correctLocation: 6, image: redPics[6], isFilled: true},
    {currentLocation: -1, correctLocation: 7, image: redPics[7], isFilled: true},
    {currentLocation: -1, correctLocation: 8, image: redPics[8], isFilled: true},
    {currentLocation: -1, correctLocation: 9, image: redPics[9], isFilled: true},
    {currentLocation: -1, correctLocation: 10, image: redPics[10], isFilled: true},
    {currentLocation: -1, correctLocation: 11, image: redPics[11], isFilled: true},
    {currentLocation: -1, correctLocation: 12, image: redPics[12], isFilled: true},
    {currentLocation: -1, correctLocation: 13, image: redPics[13], isFilled: true},
    {currentLocation: -1, correctLocation: 14, image: redPics[14], isFilled: true},
    {currentLocation: -1, correctLocation: 15, image: redPics[15], isFilled: true},
    {currentLocation: -1, correctLocation: 16, image: redPics[16], isFilled: true},
    {currentLocation: -1, correctLocation: 17, image: redPics[17], isFilled: true},
    {currentLocation: -1, correctLocation: 18, image: redPics[18], isFilled: true},
    {currentLocation: -1, correctLocation: 19, image: redPics[19], isFilled: true},
    {currentLocation: -1, correctLocation: 20, image: redPics[20], isFilled: true},
    {currentLocation: -1, correctLocation: 21, image: redPics[21], isFilled: true},
    {currentLocation: -1, correctLocation: 22, image: redPics[22], isFilled: true},
    {currentLocation: -1, correctLocation: 23, image: redPics[23], isFilled: true},
    {currentLocation: -1, correctLocation: 24, image: redPics[24], isFilled: true},
    {currentLocation: -1, correctLocation: 25, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 26, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 27, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 28, image: E00, isFilled: true},
    {currentLocation: -1, correctLocation: 29, image: E00, isFilled: true}
];

export {bluePicsArray, redPicsArray};