import {balloonsPics, ghostPics, lionPics, mansionPics, numbersPics, pencilsPics}  from "./imagesGroup";
import E00 from "./images/E00.jpg";

const balloonsPicsArray = [
    {currentLocation: null, correctLocation: 0, image: balloonsPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: balloonsPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: balloonsPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: balloonsPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: balloonsPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: balloonsPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: balloonsPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: balloonsPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: balloonsPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: balloonsPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: balloonsPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: balloonsPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: balloonsPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: balloonsPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: balloonsPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: balloonsPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: balloonsPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: balloonsPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: balloonsPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: balloonsPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: balloonsPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: balloonsPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: balloonsPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: balloonsPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: balloonsPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

const ghostPicsArray = [
    {currentLocation: null, correctLocation: 0, image: ghostPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: ghostPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: ghostPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: ghostPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: ghostPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: ghostPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: ghostPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: ghostPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: ghostPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: ghostPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: ghostPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: ghostPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: ghostPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: ghostPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: ghostPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: ghostPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: ghostPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: ghostPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: ghostPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: ghostPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: ghostPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: ghostPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: ghostPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: ghostPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: ghostPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

const lionPicsArray = [
    {currentLocation: null, correctLocation: 0, image: lionPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: lionPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: lionPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: lionPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: lionPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: lionPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: lionPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: lionPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: lionPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: lionPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: lionPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: lionPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: lionPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: lionPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: lionPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: lionPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: lionPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: lionPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: lionPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: lionPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: lionPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: lionPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: lionPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: lionPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: lionPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

const mansionPicsArray = [
    {currentLocation: null, correctLocation: 0, image: mansionPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: mansionPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: mansionPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: mansionPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: mansionPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: mansionPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: mansionPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: mansionPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: mansionPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: mansionPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: mansionPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: mansionPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: mansionPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: mansionPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: mansionPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: mansionPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: mansionPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: mansionPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: mansionPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: mansionPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: mansionPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: mansionPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: mansionPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: mansionPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: mansionPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

const numbersPicsArray = [
    {currentLocation: null, correctLocation: 0, image: numbersPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: numbersPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: numbersPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: numbersPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: numbersPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: numbersPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: numbersPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: numbersPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: numbersPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: numbersPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: numbersPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: numbersPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: numbersPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: numbersPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: numbersPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: numbersPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: numbersPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: numbersPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: numbersPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: numbersPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: numbersPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: numbersPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: numbersPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: numbersPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: numbersPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

const pencilsPicsArray = [
    {currentLocation: null, correctLocation: 0, image: pencilsPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: pencilsPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: pencilsPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: pencilsPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: pencilsPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: pencilsPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: pencilsPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: pencilsPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: pencilsPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: pencilsPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: pencilsPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: pencilsPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: pencilsPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: pencilsPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: pencilsPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: pencilsPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: pencilsPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: pencilsPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: pencilsPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: pencilsPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: pencilsPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: pencilsPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: pencilsPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: pencilsPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: pencilsPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

export {balloonsPicsArray, ghostPicsArray, lionPicsArray, mansionPicsArray, numbersPicsArray, pencilsPicsArray};