import {bluePics, redPics} from "./imagesGroup";
import E00 from "./images/E00.jpg";

const bluePicsArray = [
    {currentLocation: null, correctLocation: 0, image: bluePics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: bluePics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: bluePics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: bluePics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: bluePics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: bluePics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: bluePics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: bluePics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: bluePics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: bluePics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: bluePics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: bluePics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: bluePics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: bluePics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: bluePics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: bluePics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: bluePics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: bluePics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: bluePics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: bluePics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: bluePics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: bluePics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: bluePics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: bluePics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: bluePics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

const redPicsArray = [
    {currentLocation: null, correctLocation: 0, image: redPics[0], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 1, image: redPics[1], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 2, image: redPics[2], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 3, image: redPics[3], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 4, image: redPics[4], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 5, image: redPics[5], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 6, image: redPics[6], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 7, image: redPics[7], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 8, image: redPics[8], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 9, image: redPics[9], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 10, image: redPics[10], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 11, image: redPics[11], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 12, image: redPics[12], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 13, image: redPics[13], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 14, image: redPics[14], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 15, image: redPics[15], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 16, image: redPics[16], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 17, image: redPics[17], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 18, image: redPics[18], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 19, image: redPics[19], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 20, image: redPics[20], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 21, image: redPics[21], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 22, image: redPics[22], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 23, image: redPics[23], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 24, image: redPics[24], isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 25, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 26, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 27, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 28, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false},
    {currentLocation: null, correctLocation: 29, image: E00, isClicked: false, isSwapUpTarget: false, isSwapLeftTarget: false, isSwapDownTarget: false, isSwapRightTarget: false}
];

export {bluePicsArray, redPicsArray};